### PR TITLE
Add /usr/local/bin/python to work with FreeBSD

### PR DESCRIPTION
**Pull request by trodery**
Adding /usr/local/bin/python makes this work on FreeBSD

### CODE REVIEW

**Comment by vasiliyk** [comment]
Hello Terry.

As I understand script does not work with FreeBSD default shell tcsh.
Is there a sense to make a change if it will not work anyway on default shell?

**Comment by trodery** [comment]
It's default for me:

root@terryrodery:~ # adduser
Username: yourmom
Full name: yo momma
Uid (Leave empty for default): 
Login group [yourmom]: 
Login group is yourmom. Invite yourmom into other groups? []: 
Login class [default]: 
Shell (sh csh tcsh bash rbash git-shell nologin) [sh]: 
Home directory [/home/yourmom]: 
Home directory permissions (Leave empty for default): 
Use password-based authentication? [yes]: yes
Use an empty password? (yes/no) [no]: 
Use a random password? (yes/no) [no]: 
Enter password: 
Enter password again: 
Lock out the account after creation? [no]: no
Username   : yourmom
Password   : *****
Full Name  : yo momma
Uid        : 1002
Class      : 
Groups     : yourmom 
Home       : /home/yourmom
Home Mode  : 
Shell      : /bin/sh
Locked     : no
OK? (yes/no): yes
adduser: INFO: Successfully added (yourmom) to the user database.
Add another user? (yes/no): no
Goodbye!

**Comment by tsuna** [comment]
LGTM

**Comment by vasiliyk** [comment]
It strange FreeBSD as default proposes sh as default shell while documentation clearly states it should be tcsh https://www.freebsd.org/doc/en_US.ISO8859-1/articles/linux-users/shells.html .

I tested it with tcsh, it fails. Ok, it can work in some scenario and @tsuna is ok with that.
Merge upstream with commit https://github.com/OpenTSDB/tcollector/commit/3ba5ba987de55c183f3310fcbb3a8397eccbd84a .

Thank you for contributing.

**Pull request closed without merging**
