### PR TITLE
Added postgresql_replication collector.

### PR DESCRIPTION
**Pull request by DavidValeri**
New metrics:
- postgresql.replication.upstream.lag.time - Milliseconds since pg_last_xact_replay_timestamp
- postgresql.replication.upstream.lag.bytes - The difference, in bytes, between pg_last_xlog_receive_location and pg_last_xlog_receive_location
- postgresql.replication.downstream.count - The number of walreceivers connected to the DB
- postgresql.replication.downstream.lag.bytes - The difference, in bytes, between the sent location and the replayed location for each walreceiver
- postgresql.replication.recovering - The value of pg_is_in_recovery
- postgresql.replication.walreceiver.running - One if a walreceiver process is running on the machine, otherwise zero.

### CODE REVIEW

**Comment by johann8384** [comment]
Before your code changes can be included, please file the [Contribution License Agreement](https://docs.google.com/spreadsheet/embeddedform?formkey=dFNiOFROLXJBbFBmMkQtb1hNMWhUUnc6MQ).

**Comment by mathpl** [comment]
Anything we can do to help get this merged? Test failures appear unrelated to the actual code changes.

**Comment by vfiset** [comment]
hi @johann8384 any chance we could merge this PR? looking at the travis logs the collector we added is not the one making the tests fail.

**Comment by johann8384** [comment]
Sure, let me look at this today. I don't see why not!

**Comment by johann8384** [comment]
Merged in #385

**Pull request closed without merging**
