### PR TITLE
Update startstop script

### PR DESCRIPTION
**Pull request by benrubson**
Hello,

This pull request solves #291 / follows new configuration file style #287.

Thank you :+1: 

Ben

### CODE REVIEW

**Comment by johann8384** [comment]
Have you tested this on a few different operating systems?

**Comment by benrubson** [comment]
No, only on FreeBSD.
However, I did not introduce any new feature, I just removed unnecessary parts and corrected some bugs, keeping the existing syntax.

**Comment by johann8384** [comment]
Ok, I'll drop it onto an Ubuntu and CentOS VM then merge it. This and the CHANGELOG and I can get 1.3.1 out the door. There are a few important fixes there from the 1.3.0 release.

https://github.com/OpenTSDB/tcollector/issues?utf8=%E2%9C%93&q=milestone%3A1.3.1+

**Comment by benrubson** [comment]
Yes you're right :+1:
I just saw that you prefer to keep collectors improvements and new collectors for 1.3.2.

**Pull request merged**
