### PR TITLE
Moving Collectors to 'available' so they are not enabled by default

### LINKED ISSUE #190: Restructure of collectors/*
I would like to propose a restructuring of the /collectors directory, such that all collectors are disabled by default, but can be enabled or disabled easily, preferably without a restart of tcollector.  Without giving it too much thought, I'm leaning toward something similar to apache's a2ensite/a2enmod functionality.  By default, all collectors would be placed in the folder './collectors/available', which is essentially ignored by tcollector.  Collectors are enabled by creating a symlink from ./collectors/0/collector.py to ./collectors/available/collector.py.  Collectors are disable by removing the symlink (this would require changes to tcollector.py to look for modules that are running, but which a symlink does not exist for, and kill the collector if it doesn't exit on its own after a certain time).

I would also like to propose refactoring the config file, to be directly tied to the collector, though I have less of a suggestion on how to structure this; perhaps combining both the config and code into a single folder that is placed under the collectors directory, ie, ./collectors/0/my_collector.d/{main.py|config.py}. However, I am also contemplating placing configs in /etc/tcollector/module_name/, and other alternatives.

Background:  We have a VM farm of about 15 "development environments", which are one or more hosts that mimic our multi-host production environment.  Each development team has access to 1 or 2 of these dev environments.  I would like to use tcollector to gather metrics from each development environment so that the development teams can monitor the status of their environment.

In order to manage these 20 hosts, I would like to deploy tcollector via puppet.  Since some collectors require specific configuration changes (database config, custom tags, etc), and due to current, active development of new collectors specific to our environment, I'm configuring puppet to clone tcollector from our local fork of the github repo; and then template the individual configs.  I intend to use the same fork to submit patches back to the master, so I don't want to store our custom configs in our tcollector repo.  Likewise, however, I do not want new collectors and configs coming down-stream and automatically being included and executed.  Additinally, I have ran into problems in the past where an invalid module config for a disabled collector will bring down tcollector completely due to tcollector evaluating all configs in ./collector/etc, regardless of whether the parent collector is enabled or not.

I would certainly like to have a further discussion of this, and see where the rest of the OpenTSDB/tcollector team is with this.  I am happy to do the refactoring and code contributions where I am able.  If this issue-request isn't the best place for that discussion, please direct me to the proper channel.

### PR DESCRIPTION
**Pull request by johann8384**
Closes #190

### CODE REVIEW

**Comment by johann8384** [comment]
@tsuna @vasiliyk I'd prefer one of you weigh in on these rather than merge my own PR.

**Comment by tsuna** [comment]
So is the expectation that distributions will package all these collectors using the `available` directory and that after installation, the system operators will symlink them into the `0` directory to enable the collectors of their choice (perhaps with Puppet or Chef or whatever, or manually)?

**Comment by johann8384** [comment]
Yes, I think I'll modify it to be a little different, like maybe have an "available", an "osx", a "freebsd" and try to put the current collectors in available and then the os specific ones in the other two folders. 

I'm not 100% sure how this one will work out yet, and I need to properly coordinate it with the packaging so that it works.

I'm planning to build a build pipeline that will use Docker to build for RPM and DEB packages. I suspect I can integrate the Arista EOS build into that also.

**Comment by benrubson** [comment]
What about the following tree ?

```
collectors/
┗ 0/
┗ 60/
┗ 3600/
  (...)
┗ available/
  ┗ long-lived/
    ┗ linux/
    ┗ freebsd/
    ┗ macos/
    ┗ softwares/
  ┗ one-shot/
    ┗ linux/
    ┗ freebsd/
    ┗ macos/
    ┗ softwares/
```

**Comment by johann8384** [comment]
That is the best I layout I have seen so far, but I feel like there is a better way still.

**Comment by benrubson** [comment]
An Apache style ?

```
collectors-available/
┗ linux/
  ┗ long-lived/
  ┗ one-shot/
┗ freebsd/
  ┗ long-lived/
  ┗ one-shot/
┗ osx/
  ┗ long-lived/
  ┗ one-shot/
┗ softwares/
  ┗ long-lived/
  ┗ one-shot/
collectors-enabled/
┗ 0/
┗ 60/
┗ 3600/
┗ (...)
collectors-etc/
```
With logical links from `collectors-enabled` subfolders to `collectors-available` subfolders to enable modules.
And a `collectors-etc` folder to contain modules configuration files.

**Comment by johann8384** [comment]
What about collectors that work on OSX and Linux, but not FreeBSD? (or some such thing)

**Comment by johann8384** [comment]
I guess the packaging/install script could enable a set of collectors by default based on the OS. Or, we could have:

collectors-available/
┗ global/
  ┗ long-lived/
  ┗ one-shot/
┗ linux/
  ┗ long-lived/
  ┗ one-shot/
┗ freebsd/
  ┗ long-lived/
  ┗ one-shot/
┗ osx/
  ┗ long-lived/
  ┗ one-shot/
┗ softwares/
  ┗ long-lived/
  ┗ one-shot/
collectors-enabled/
┗ 0/
┗ 60/
┗ 3600/
┗ (...)
collectors-etc/

**Comment by benrubson** [comment]
Yes you're right, the `global` makes sense :+1:

**Comment by benrubson** [comment]
`global` or `all_os`, perhaps more precise...

**Comment by vasiliyk** [comment]
@johann8384 , thank you for putting it all together!!

I like the proposed structure and idea to enable global + OS specific collectors in packaging/install script.
What help do you need to finalize PR?

**Comment by vasiliyk** [comment]
implemented and merged with the commit https://github.com/OpenTSDB/tcollector/commit/881e2157dfbdc9e7e9f7160508e41f454e0b0bb7

**Pull request closed without merging**
