### PR TITLE
New collector : detailed % CPU statistics

### PR DESCRIPTION
**Pull request by benrubson**
Hello,

Here is a new collector.

It tracks, for all CPUs:
- user %
- nice %
- system %
- interrupt %
- idle %

Works on FreeBSD thanks to a nicely improved `top` command.
Here is the command used : `top -t -I -P -n -s15 -d40320`
Unfortunately, Linux top command does not understand these parameters.

Thank you !

Ben

### CODE REVIEW

**Comment by johann8384** [comment]
Will the Linux TOP command be abel to show these in a future version perhaps? Or is there another way to get the same data?

If not, perhaps we could utilize platform.system() to make a collector that transparently worked on both platforms outputting as much data as possible for each?

**Comment by benrubson** [comment]
Here it is, now compatible with Linux :+1:
I use `mpstat` under Linux to get the same counter as with `top` under FreeBSD.

**Comment by johann8384** [comment]
Adjust the configured interval to 15 and I'll merge it!

**Comment by benrubson** [comment]
Why do you prefer 15 seconds ?
10 allows fine tracking of CPU usage, then we can easily downsample for long range studies through the OpenTSDB request.

**Comment by johann8384** [comment]
15 seconds is the smallest interval TCollector will actually run (for non-long running collectors) and 10 is just a very aggressive default setting. I was tempted to say 60, but 15 feels OK. You can leave it at 10 I guess. It's just a lot more often than needed for a default value.

When you have systems with thousands of systems reporting and millions of datapoints per second coming in, you really think hard about "how often do I *really* need that value collected?" because one aggressive default adds a lot more data to process.

**Comment by johann8384** [comment]
Merged.

**Comment by johann8384** [comment]
I did a quick look at intervals in the configs and most were 15, 60 and a few were 20 and 25. The jolokia one was 10. I set the interval to 15 for the default.

Obviously, your CM tool can set this to any value you want on your environment.

**Pull request closed without merging**
