### PR TITLE
Python 2.6, 2.7, 3.4, 3.5, 3.6, 3.7 compatibility

### PR DESCRIPTION
**Pull request by xavierhardy**
This pull request brings compatibility from Python 3.4 to Python 3.7 included (`await` is keyword in 3.7).

### CODE REVIEW

**Comment by xavierhardy** [comment]
Related to issue #218

**Comment by johann8384** [comment]
This is great! I did some work on this as well, and did some refactoring to make testing easier. I'll rebase mine to work off this, you went through more collectors than I had gotten to.

**Comment by johann8384** [comment]
Can you add the additional Python version to the Travis build in your branch? Then we can see that is passes with all the versions for your PR.

https://github.com/OpenTSDB/tcollector/blob/master/.travis.yml#L3

Thank you !!

**Comment by johann8384** [comment]
Merged in #411

**Pull request closed without merging**
