### PR TITLE
Collector for MapR Hadoop node metrics.

### PR DESCRIPTION
**Pull request by johann8384**
Fixes #196

### CODE REVIEW

**Comment by johann8384** [comment]
I moved this to 1.3.1 as I don't have a good way to test it. @vicenteg would you be able to pull down this after the changes I made and test it?

I'd really like to see a text file attached of the new metrics. I typically get this by dumping the output of one run and piping to:

```awk '{print #2}' | sort | uniq```

You can run a single collector like this:

``bash -c "PYTHONPATH=$PYTHONPATH:./collectors/lib:./ python collectors/0/mapr_metrics.py"```

I apologize if you already know all this, just trying to be helpful! :)

**Comment by vicenteg** [comment]
I appreciate the help!

Is there a naming convention you prefer for metrics?

**Comment by johann8384** [comment]
Well, very generically I use the metric name for a metric and tags create a specific instance of that metric.

Ex name: 

net.io
docker.memory.used

Ex tags:

net.io direction=in host=hostname interface=interfacename
docker.memory.used type=rss
docker.memory.used type=cache

**Comment by vicenteg** [comment]
Sorry for the long delay.

The collector with your changes does work against my MapR v5.1 cluster. Here's the list of metrics (I had to modify your awk pipeline to print $1, hope the below is what you were expecting):

```
mapr.cpus.CPUIDLE
mapr.cpus.CPUIOWAIT
mapr.cpus.CPUTOTAL
mapr.disks.READBYTES
mapr.disks.READOPS
mapr.disks.WRITEBYTES
mapr.disks.WRITEOPS
mapr.memory.used
mapr.mfs.available
mapr.mfs.used
mapr.network.BYTESIN
mapr.network.BYTESOUT
mapr.network.PKTSIN
mapr.network.PKTSOUT
mapr.rpc.count
mapr.rpc.inbytes
mapr.rpc.outbytes
```

**Pull request merged**
