### PR TITLE
Update RPM packaging

### PR DESCRIPTION
**Pull request by phil-arista**
- Enable RPM subpackages. Allows you to create 3 packages
  - A base package with the just the tcollector
  - A collectors subpackage with just collectors
  - An eos subpackage with EOS-only collectors (depends on EosSDK)

### CODE REVIEW

**Comment by phil-arista** [comment]
Now when you do ``make rpm`` you get three RPMS in the noarch dir:

The base RPM tcollector-1.2.1-1.noarch.rpm 
```
[root@ztps noarch]# rpm -qlp tcollector-1.2.1-1.noarch.rpm 
/etc/init.d/tcollector
/usr/local/tcollector
/usr/local/tcollector/collectors/__init__.py
/usr/local/tcollector/collectors/etc
/usr/local/tcollector/collectors/etc/__init__.py
/usr/local/tcollector/collectors/etc/config.py
/usr/local/tcollector/collectors/etc/flume_conf.py
/usr/local/tcollector/collectors/etc/g1gc_conf.py
/usr/local/tcollector/collectors/etc/graphite_bridge_conf.py
/usr/local/tcollector/collectors/etc/jolokia_conf.py
/usr/local/tcollector/collectors/etc/mysqlconf.py
/usr/local/tcollector/collectors/etc/postgresqlconf.py
/usr/local/tcollector/collectors/etc/udp_bridge_conf.py
/usr/local/tcollector/collectors/etc/zabbix_bridge_conf.py
/usr/local/tcollector/collectors/lib
/usr/local/tcollector/collectors/lib/__init__.py
/usr/local/tcollector/collectors/lib/hadoop_http.py
/usr/local/tcollector/collectors/lib/utils.py
/usr/local/tcollector/tcollector.py
```

The collectors subpackage tcollector-collectors-1.2.1-1.noarch.rpm 
```
[root@ztps noarch]# rpm -qlp tcollector-collectors-1.2.1-1.noarch.rpm 
/usr/local/tcollector/collectors/0/dfstat.py
/usr/local/tcollector/collectors/0/ifstat.py
/usr/local/tcollector/collectors/0/iostat.py
/usr/local/tcollector/collectors/0/netstat.py
/usr/local/tcollector/collectors/0/procnettcp.py
/usr/local/tcollector/collectors/0/procstats.py
/usr/local/tcollector/collectors/0/smart-stats.py
```

The EOS subpackage tcollector-eos-1.2.1-1.noarch.rpm 
```
[root@ztps noarch]# rpm -qlp tcollector-eos-1.2.1-1.noarch.rpm 
/usr/bin/tcollector
/usr/lib/python2.7/site-packages/tcollector_agent.py
/usr/local/tcollector/collectors/0/agentcpu.sh
/usr/local/tcollector/collectors/0/eos.py
```

**Comment by johann8384** [comment]
This is a silly question probably, but you've completed the CLA right?

**Comment by phil-arista** [comment]
CLA?

**Comment by johann8384** [comment]
The OpenTSDB Contributor License Agreement
https://docs.google.com/forms/d/1VVqKFTYNp3btgwXE51Zf9_Sfq66yZ4JbuEFrLlTD70E/viewform?embedded=true&formkey=dFNiOFROLXJBbFBmMkQtb1hNMWhUUnc6MQ

**Pull request merged**
