### PR TITLE
add TCP(IPv4 + IPv6) socket state metrics

### PR DESCRIPTION
**Pull request by meow-watermelon**

### CODE REVIEW

**Comment by meow-watermelon** [comment]
This PR adds detailed TCP socket state count metrics. Output example:

```
...
net.tcp_state.established 8 1651898418 type=tcp
net.tcp_state.syn_sent 0 1651898418 type=tcp
net.tcp_state.syn_recv 0 1651898418 type=tcp
net.tcp_state.fin_wait1 0 1651898418 type=tcp
net.tcp_state.fin_wait2 0 1651898418 type=tcp
net.tcp_state.time_wait 0 1651898418 type=tcp
net.tcp_state.close 0 1651898418 type=tcp
net.tcp_state.close_wait 0 1651898418 type=tcp
net.tcp_state.last_ack 0 1651898418 type=tcp
net.tcp_state.listen 5 1651898418 type=tcp
net.tcp_state.closing 0 1651898418 type=tcp
net.tcp_state.new_syn_recv 0 1651898418 type=tcp
net.tcp_state.max_states 0 1651898418 type=tcp
net.tcp_state.established 1 1651898418 type=tcp6
net.tcp_state.syn_sent 0 1651898418 type=tcp6
net.tcp_state.syn_recv 0 1651898418 type=tcp6
net.tcp_state.fin_wait1 0 1651898418 type=tcp6
net.tcp_state.fin_wait2 0 1651898418 type=tcp6
net.tcp_state.time_wait 4 1651898418 type=tcp6
net.tcp_state.close 0 1651898418 type=tcp6
net.tcp_state.close_wait 0 1651898418 type=tcp6
net.tcp_state.last_ack 0 1651898418 type=tcp6
net.tcp_state.listen 3 1651898418 type=tcp6
net.tcp_state.closing 0 1651898418 type=tcp6
net.tcp_state.new_syn_recv 0 1651898418 type=tcp6
net.tcp_state.max_states 0 1651898418 type=tcp6
```

The `type` indicates if the metric is from IPv4(`tcp`) or IPv6(`tcp6`) socket.

**Comment by meow-watermelon** [comment]
@johann8384 @tsuna could you please take a look? Thanks.

**Comment by meow-watermelon** [comment]
@manolama could you please take a look? Thanks

**Comment by vasiliyk** [comment]
Thank you for contributing!

Right now I see the following error that netstat collector produces:
`"Unrecoginized line in /proc/net/netstat: ['MPTcpExt:'"`.
 As I understand it is Multipath TCP. I need to fix it before adding the enhancement. Are you interested in fixing it?

**Comment by meow-watermelon** [comment]
hi @vasiliyk sure, i will do the fix soon. i think because it's been almost 2 years so need some adjustments.

**Comment by vasiliyk** [comment]
Merged with commits https://github.com/OpenTSDB/tcollector/commit/0317149bd7d914e95bdc846a01c8c5176e48d9a6 and https://github.com/OpenTSDB/tcollector/commit/ce0947257f08ecfedc52147ed1061420375c9cb1.

**Pull request closed without merging**
