### PR TITLE
elasticsearch: add ES 1.6.x metrics

### PR DESCRIPTION
**Pull request by Filirom1**
Hello

This PR add new metrics that are available on ES 1.6.x

Cheers

### CODE REVIEW

**Comment by johann8384** [comment]
Have you completed the Contributor License Agreement? These changes look good and I can merge them when that is complete.

https://docs.google.com/spreadsheet/embeddedform?formkey=dFNiOFROLXJBbFBmMkQtb1hNMWhUUnc6MQ

**Comment by johann8384** [comment]
bump

**Comment by Filirom1** [comment]
@johann8384 I just did it now.

**Comment by johann8384** [comment]
Merged.

**Pull request closed without merging**
